name: Scala CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java and sbt
        uses: coursier/setup-action@v1
        with:
          jvm: temurin:17
          apps: sbt

      - name: Run tests
        run: sbt test